In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[0:3])

[1 2 3]


In [12]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[1,0:3])
print(a[1,2])

[6 7 8]
8


In [13]:
import numpy as np
a=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[21,22,23,24,25]]])
print(a[1,0,1:4])
print(a[1,0,2])

[12 13 14]
13


In [8]:
import numpy as np
l=np.array([2,3,4,5,6])
print(l)
print(l.ndim)

[2 3 4 5 6]
1


In [9]:
import numpy as np
l=np.array([[2,3,4,5,6],[7,8,9,10,11]])
print(l)
print(l.ndim)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]
2


In [14]:
import numpy as np
l=np.array([[[2,3,4,5,6],[7,8,9,10,11]],[[1,2,3,4,5],[6,7,8,9,0]]])
print(l)
print(l.ndim)

[[[ 2  3  4  5  6]
  [ 7  8  9 10 11]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9  0]]]
3


In [17]:
import numpy as np
l=np.array([[[2,3,4,5,6],[7,8,9,10,11]],[[1,2,3,4,5],[6,7,8,9,0]]])
print(l[0,1,0:4])

[ 7  8  9 10]


In [18]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [21]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[2])

3
